### ISSUE TITLE
No python in seed node.

### ISSUE THREAD

**Issue by jingvar** [stackhpc/a-universe-from-nothing#84] opened 2021-05-26 13:38 UTC
/dev/seed-deploy.sh

TASK [singleplatform-eng.users : Per-user group creation]
 "Shared connection to 192.168.33.5 closed.\r\n", "module_stdout": "/bin/sh: /usr/bin/python3: No such file or directory\r\n", "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", "rc": 127}

I login  in seed node , manually install python and rerun /dev/seed-deploy.sh and the error is gone

**Comment by priteau** [comment] 2021-05-26 14:23
Thank you @jingvar for the report. Could you please tell us which branch of this repository you are using and what QCOW2 image was used to create the seed VM?

**Comment by jingvar** [comment] 2021-05-26 16:39
I used your docs, step by step.

commit 37ab622cde3ad7b0e1b3b703f688cd24a0899ba2 (HEAD -> stable/victoria, origin/stable/victoria)
* stable/victoria

ansible/group_vars/all/seed-vm:seed_vm_root_image: "https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-GenericCloud-8.3.2011-20201204.2.x86_64.qcow2"

**Comment by markgoddard** [comment] 2021-05-27 09:52
Very strange. I thought the CentOS cloud images came with python3 installed.

We did add support in Wallaby for bootstrapping python: https://opendev.org/openstack/kayobe/src/commit/6b65b29395b798eed735661a03146798569639d3/ansible/kayobe-ansible-user.yml#L38. Perhaps it needs to be backported.

**Comment by priteau** [comment] 2021-05-27 10:55
I've booted the CentOS 8.3 image and Python is indeed missing:

```
$ python
-bash: python: command not found
$ python3
-bash: python3: command not found
```

**Comment by priteau** [comment] 2021-05-27 11:06
Actually, it's the same with earlier images. But `/usr/libexec/platform-python` is available.

**Comment by priteau** [comment] 2021-05-27 11:08
So this is most likely caused by https://review.opendev.org/c/openstack/kayobe/+/789753

**Comment by priteau** [comment] 2021-05-28 07:10
@jingvar Could you try this patch? https://review.opendev.org/c/openstack/kayobe/+/793402

**Comment by jingvar** [comment] 2021-05-31 13:27
I've checked it.  Now I having deployed seed node without issue with python. But faced with another one. I'm not sure that it related with topic.

**Comment by priteau** [comment] 2021-06-02 15:33
This is now fixed upstream: https://review.opendev.org/c/openstack/kayobe/+/793402

**Closed by priteau** 2021-06-02 15:33 UTC
